<?php
//IP DE LA PC SERVIDOR DE BASE DE DATOS
define("DB_HOST","localhost");

//NOMBRE DE LA BASE DE DATOS
define("DB_NAME","sistema");

//USUARIO DE LA BASE DE DATOS
define("DB_USERNAME","root");

//CONTRASEÑA DEL USUARIO DE LA BASE DE DATOS
define("DB_PASSWORD","");

//SE DEFINE CODIFICACIÓN DE LOS CARACTERES
define("DB_ENCODE","utf8");

//SE DEFINE UNA CONSTANTE COMO NOMBRE DEL PROYECTO
define("PRO_NOMBRE","SIAAC");


?>